apiVersion: v1
kind: Service
metadata:
  name: epicbites-web-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:206849463638:certificate/585d724e-c626-4268-bc49-0b8a3a1d2baf
    # Only run TLS on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 'https'
spec:
  selector:
    app: epicbites-web
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicbites-web-deploy
  labels:
    app: epicbites-web
spec:
  selector:
    matchLabels:
      app: epicbites-web
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: epicbites-web
        tier: frontend
    spec:
      containers:
        - name: epicbites-web
          image: patriciaabad/epicbites-web:9.0
          ports:
            - containerPort: 80
