apiVersion: v1
kind: Service
metadata:
  name: epicbites-web-svc
  labels:
    app: epicbites-web
spec:
  ports:
    - port: 80
  selector:
    app: epicbites-web
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicbites-web-deploy
  labels:
    app: epicbites-web
spec:
  selector:
    matchLabels:
      app: epicbites-web
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: epicbites-web
        tier: frontend
    spec:
      containers:
        - name: epicbites-web
          image: patriciaabad/epicbites-web:3.0
          ports:
            - containerPort: 80
